version: '3.4'
services:
  ## Override start commands for app and app-client to use polling strategies in windows machines
  app:
    command: bash -c "npm install && npm run start:server-win"
  app-client:
    command: bash -c "npm install && npm run start:client-win"
